#!/usr/bin/env node
/* ==========================================================================
   scripts/changelog.js — fills the generated half of changelog.html from the
   git history.
   --------------------------------------------------------------------------
       node scripts/changelog.js            rewrite the committed page
       node scripts/changelog.js --check    report drift, write nothing (exit 1)

   Same arrangement glossary.js already has with the glossary, and for the
   same reason. The page is part hand-written and part generated, and the
   split is marked in the HTML itself:

     <!-- changelog:start -->  …every entry…  <!-- changelog:end -->

   Everything outside those markers — the head, the hero, the static header
   and footer — is hand-written and never touched here.

   WHY GENERATED AND NOT WRITTEN. A hand-kept changelog is a changelog that
   stops being kept: it survives three releases, then one busy week, then it
   is a page that says the site last changed in March. The commit messages
   already exist, they are already written carefully, and they are already
   the truth. Reading them is strictly better than asking someone to write
   the same thing twice and trusting the second copy.

   WHICH IS ALSO THE LIMIT. This is only as good as the commit subjects, and
   it will happily publish a subject that says "fix". The answer to that is
   to keep writing good ones, not to add a second place to maintain.

   GROUPED BY MONTH, NOT LISTED FLAT. Two hundred entries in one column is a
   log, not a page. Month headings give it a shape a person can skim, and the
   count per month is the figure that actually says how the site is going.

   MERGE COMMITS ARE DROPPED and so is anything that reads as pure
   housekeeping, because "Merge branch 'main'" tells a visitor nothing. The
   filter is deliberately short: a changelog that hides most of its own
   history is a marketing page.
   ========================================================================== */

'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const PAGE = path.join(ROOT, 'changelog.html');
const START = '<!-- changelog:start — generated by scripts/changelog.js, do not hand-edit -->';
const END = '<!-- changelog:end -->';

/* Subjects that are true, committed, and of no interest to a reader. */
const SKIP = /^(merge\b|wip\b|typo$|fixup!|squash!)/i;

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'];

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function history() {
  /* %x1f between fields and %x1e between records: git's own unit and record
     separators, so a commit subject containing a pipe or a tab cannot split
     a row. Subjects on this repository routinely contain both. */
  const raw = execFileSync('git',
    ['log', '--no-merges', '--date=short', '--pretty=format:%h%x1f%ad%x1f%s%x1e'],
    { cwd: ROOT, encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 });

  return raw.split('\x1e')
    .map((r) => r.trim())
    .filter(Boolean)
    .map((r) => {
      const [hash, date, subject] = r.split('\x1f');
      return { hash, date, subject: (subject || '').trim() };
    })
    .filter((c) => c.subject && !SKIP.test(c.subject));
}

function render(commits) {
  const groups = [];
  let current = null;

  for (const c of commits) {
    const key = c.date.slice(0, 7);
    if (!current || current.key !== key) {
      const [y, m] = key.split('-');
      current = { key, label: MONTHS[Number(m) - 1] + ' ' + y, items: [] };
      groups.push(current);
    }
    current.items.push(c);
  }

  const out = [];
  out.push('        <div class="section-heading">');
  out.push('          <h2>' + commits.length + ' changes across ' + groups.length + ' months</h2>');
  out.push('          <p>Newest first. Every line is a commit subject, unedited.</p>');
  out.push('        </div>');

  for (const g of groups) {
    out.push('        <h3 class="changelog-month">' + esc(g.label) +
      ' <span class="changelog-count">' + g.items.length + '</span></h3>');
    out.push('        <ul class="changelog-list">');
    for (const c of g.items) {
      out.push('          <li><span class="changelog-date">' + esc(c.date) +
        '</span> ' + esc(c.subject) + '</li>');
    }
    out.push('        </ul>');
  }
  return out.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const src = fs.readFileSync(PAGE, 'utf8');
  const a = src.indexOf(START);
  const b = src.indexOf(END);

  if (a === -1 || b === -1 || b < a) {
    throw new Error('changelog.js: markers missing from changelog.html — refusing to guess where the generated half goes');
  }

  const commits = history();
  if (!commits.length) {
    throw new Error('changelog.js: git returned no usable commits — refusing to publish an empty changelog');
  }

  const next = src.slice(0, a + START.length) + '\n' + render(commits) + '\n        ' + src.slice(b);

  if (next === src) {
    console.log('changelog\n  ' + commits.length + ' entries, already current');
    return;
  }
  /* Reported, not fatal — unlike glossary.js, which throws on drift.

     The difference is what causes it. The glossary only drifts when somebody
     edits the term list and forgets to run the generator, which is a mistake
     worth blocking a deploy over. This page drifts every single time anything
     is committed, including by the commit that regenerates it, so a strict
     check would fail `npm run check` permanently and for no fault. The deploy
     rebuilds it from the container's own git history, so a stale committed
     copy never reaches a visitor. */
  if (check) {
    console.log('changelog\n  committed copy is behind; the deploy will rebuild it with ' +
      commits.length + ' entries');
    return;
  }
  fs.writeFileSync(PAGE, next);
  console.log('changelog\n  wrote ' + commits.length + ' entries');
}

main();
