/* ==========================================================================
   scripts/glossary.js — rebuilds the generated half of glossary.html from
   scripts/glossary-terms.js.
   --------------------------------------------------------------------------
   The page is part hand-written and part generated, and the split is marked in
   the HTML itself:

     <!-- glossary:ld:start -->  …the DefinedTermSet JSON-LD…  <!-- glossary:ld:end -->
     <!-- glossary:start -->     …the A–Z bar and every entry… <!-- glossary:end -->

   Everything outside those markers — the head, the hero copy, the filter
   chips, the static header and footer — is hand-written and is never touched
   by this script. Everything inside is overwritten wholesale, so do not hand
   edit it: 144 entries is well past the point where a person keeps an
   alphabetised list correct by hand, which is the whole reason this exists.

   Adding a term is one entry in glossary-terms.js and one run of this script.

       node scripts/glossary.js            rewrite the committed page
       node scripts/glossary.js --check    report drift, write nothing (exit 1)

   Four things are refused rather than published, because each one produced a
   page that looked fine and was wrong:

     - a cross-reference (`see`) naming a term that does not exist, which
       renders as a link to nowhere
     - two entries with the same name, which makes one of the two #term-
       anchors unreachable
     - a category that has no chip on the page, so those entries can never be
       filtered to
     - a `lab` or `post` slug with no file behind it — the one failure a
       reader meets as a 404 rather than as a cosmetic flaw

   The last of these is why the slug check reads the filesystem instead of
   trusting the data file: /labs and /blog are served as clean URLs, so a
   typo'd slug is indistinguishable from a real one until someone clicks it.
   ========================================================================== */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PAGE = path.join(ROOT, 'glossary.html');
const BASE = 'https://krunalkumar.dpdns.org';
const terms = require('./glossary-terms.js');

// Category key -> the chip label on the page. A key missing here is refused:
// it would render entries no filter can reach.
const CATS = {
  security: 'Security &amp; attacks',
  crypto: 'Cryptography',
  network: 'Networking',
  forensics: 'Forensics',
  systems: 'Systems &amp; OS',
  dev: 'Programming',
  compliance: 'Law &amp; compliance',
  career: 'Career &amp; business',
};

const LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

// Leaves existing entities alone (&amp; stays &amp;, never &amp;amp;).
const esc = (s) =>
  String(s).replace(/&(?![a-z]+;|#\d+;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const deaccent = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '');
const slug = (s) => deaccent(s.toLowerCase()).replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// 'base' sensitivity so bcrypt files under B and Vigenère under V.
const sorted = terms.slice().sort((a, b) => a.t.localeCompare(b.t, 'en', { sensitivity: 'base' }));

const firstLetter = (t) => {
  const c = deaccent(t.t)[0].toUpperCase();
  return /[A-Z]/.test(c) ? c : '#';
};

function validate() {
  const names = new Set(sorted.map((x) => x.t));
  const seen = new Set();
  const problems = [];

  for (const x of sorted) {
    const key = x.t.toLowerCase();
    if (seen.has(key)) problems.push('duplicate term: ' + x.t);
    seen.add(key);

    if (!CATS[x.c]) problems.push(x.t + ': category "' + x.c + '" has no chip on the page');

    for (const r of x.see || []) {
      if (!names.has(r)) problems.push(x.t + ': cross-reference to a term that does not exist — ' + r);
    }
    if (x.lab && !fs.existsSync(path.join(ROOT, 'labs', x.lab + '.html'))) {
      problems.push(x.t + ': lab slug has no file behind it — /labs/' + x.lab);
    }
    if (x.post && !fs.existsSync(path.join(ROOT, 'blog', x.post + '.html'))) {
      problems.push(x.t + ': post slug has no file behind it — /blog/' + x.post);
    }
  }
  return problems;
}

function buildBody() {
  const used = new Set(sorted.map(firstLetter));
  let out = '        <!-- glossary:start — generated by scripts/glossary.js, do not hand-edit -->\n';

  out += '      <nav class="glossary-az" aria-label="Jump to letter">\n';
  for (const L of LETTERS) {
    // A letter with no entries stays in the bar but inert: a gap in the
    // alphabet reads as a rendering fault, an unavailable letter reads as
    // an answer.
    out += used.has(L)
      ? `        <a class="glossary-az-link" href="#letter-${L.toLowerCase()}">${L}</a>\n`
      : `        <span class="glossary-az-link is-empty" aria-disabled="true">${L}</span>\n`;
  }
  out += '      </nav>\n\n';

  for (const L of LETTERS.filter((x) => used.has(x))) {
    const low = L.toLowerCase();
    out += `      <section class="glossary-group" id="letter-${low}" aria-labelledby="letter-${low}-h">\n`;
    out += `        <h2 class="glossary-letter" id="letter-${low}-h">${L}<a class="glossary-top" href="#glossary-top" aria-label="Back to top of glossary">&uarr;</a></h2>\n`;
    out += '        <dl class="glossary-list">\n';

    for (const x of sorted.filter((t) => firstLetter(t) === L)) {
      out += `          <div class="glossary-item" id="term-${slug(x.t)}" data-cat="${x.c}">\n`;
      out += `            <dt class="glossary-term">${esc(x.t)}<span class="glossary-tag" data-cat="${x.c}">${CATS[x.c]}</span></dt>\n`;
      out += `            <dd class="glossary-def">\n              <p>${esc(x.d)}</p>\n`;

      const links = [];
      if (x.lab) links.push(`<a class="glossary-link glossary-link--lab" href="/labs/${x.lab}">See it work</a>`);
      if (x.post) links.push(`<a class="glossary-link glossary-link--post" href="/blog/${x.post}">Read more</a>`);
      if (links.length) out += `              <p class="glossary-links">${links.join('\n              ')}</p>\n`;

      if (x.see && x.see.length) {
        const refs = x.see.map((r) => `<a href="#term-${slug(r)}">${esc(r)}</a>`).join(', ');
        out += `              <p class="glossary-see">See also: ${refs}</p>\n`;
      }
      out += '            </dd>\n          </div>\n';
    }
    out += '        </dl>\n      </section>\n\n';
  }
  out += '        <!-- glossary:end -->';
  return out;
}

function buildLd() {
  const ld = {
    '@context': 'https://schema.org',
    '@type': 'DefinedTermSet',
    '@id': BASE + '/glossary#termset',
    name: 'Security, Systems & Code Glossary',
    description:
      'Plain-language definitions of ' + sorted.length +
      ' security, networking, forensics, systems and programming terms, each linked to a hands-on lab or article that demonstrates it.',
    url: BASE + '/glossary',
    // Term entries carry name + url only. The definitions sit in the visible
    // markup directly below; repeating all of them here doubled the page
    // weight for no crawler that reads one and not the other.
    hasDefinedTerm: sorted.map((x) => ({
      '@type': 'DefinedTerm',
      name: x.t,
      url: BASE + '/glossary#term-' + slug(x.t),
    })),
  };
  const body = JSON.stringify(ld, null, 2).split('\n').map((l) => '      ' + l).join('\n');
  return '    <!-- glossary:ld:start — generated by scripts/glossary.js, do not hand-edit -->\n' +
         '    <script type="application/ld+json">\n' + body + '\n    </script>\n' +
         '    <!-- glossary:ld:end -->';
}

function replaceRegion(src, startMark, endMark, next, label) {
  const a = src.indexOf(startMark);
  const b = src.indexOf(endMark);
  if (a < 0 || b < 0) {
    throw new Error('glossary: could not find the ' + label + ' markers in glossary.html — refusing to write');
  }
  return src.slice(0, a) + next + src.slice(b + endMark.length);
}

function main() {
  const check = process.argv.includes('--check');
  console.log('glossary');

  const problems = validate();
  if (problems.length) {
    problems.forEach((p) => console.log('    - ' + p));
    console.error('  FAILED: ' + problems.length + ' problem(s) — nothing written');
    process.exit(1);
  }

  const src = fs.readFileSync(PAGE, 'utf8');
  let out = replaceRegion(src, '    <!-- glossary:ld:start', '<!-- glossary:ld:end -->', buildLd(), 'JSON-LD');
  out = replaceRegion(out, '        <!-- glossary:start', '<!-- glossary:end -->', buildBody(), 'body');

  const counts = {};
  sorted.forEach((x) => { counts[x.c] = (counts[x.c] || 0) + 1; });
  const used = [...new Set(sorted.map(firstLetter))].sort();

  const empty = LETTERS.filter((L) => !used.includes(L));
  console.log('  ' + sorted.length + ' terms, ' + used.length + ' letters in use, ' +
              (empty.length ? empty.join('') + ' empty' : 'none empty'));
  console.log('  ' + Object.entries(counts).map(([k, v]) => k + '=' + v).join(', '));
  console.log('  ' + sorted.filter((x) => x.lab).length + ' link to a lab, ' +
              sorted.filter((x) => x.post).length + ' to an article, ' +
              sorted.reduce((n, x) => n + (x.see ? x.see.length : 0), 0) + ' cross-references');

  if (out === src) { console.log('  page already current, nothing to write'); return; }
  if (check) {
    console.error('  DRIFT: glossary.html does not match glossary-terms.js — run `npm run glossary`');
    process.exit(1);
  }
  fs.writeFileSync(PAGE, out, 'utf8');
  console.log('  wrote glossary.html (' + out.length + ' bytes)');
}

main();
